### ISSUE TITLE
访问网络图片时，会把图片地址在轮播图下方展示出来

### ISSUE THREAD

**Issue by KissKun** [fazhongxu/IBannerView#1]
访问网络图片时，会把图片地址展示出来  
![f q4sn9ik hr 3h9 n323qg](https://user-images.githubusercontent.com/33314946/46002422-992ef980-c0e0-11e8-9186-93d32e4115fb.png)

**Comment by fazhongxu** [comment]
可以设置透明，小圆点颜色，
