### ISSUE TITLE
如何设置两张图片之间的间距

### ISSUE THREAD

**Issue by KissKun** [fazhongxu/IBannerView#2]
感觉两张图片间距太小，怎么设置的大些

**Comment by fazhongxu** [comment]
@KissKun mBannerViewPager.setPageMargin  bannerview源码里面，有空我暴露一下设置方法，你着急可以下载源码去修改，bannerview 
里面的 mBannerViewPager.setPageMargin 这个值，目前是写死的10

**Comment by fazhongxu** [comment]
@KissKun  两张图片之间的距离已经加上了 升级到v0.1.7 就好了 对应属性 app:pictureSpacing="10"

**Comment by Xinan1989** [comment]
可以加上这个中间图片放大效果
1、attrs中配置是否支持缩放isScale.
2、public class BannerTransformer implements ViewPager.PageTransformer {
    private static final float MAX_SCALE = 1.1f;
    private static final float MIN_SCALE = 0.9f;

    @Override
    public void transformPage(View page, float position) {
        if (position < -1) {//(-Infinity,-1)
            page.setScaleX(MIN_SCALE);
            page.setScaleY(MIN_SCALE);
        } else if (position <= 0) {//[-1,0]
            float scaleFactor =  MIN_SCALE+(1-Math.abs(position))*(MAX_SCALE-MIN_SCALE);
            page.setScaleX(scaleFactor);
            page.setScaleY(scaleFactor);
        } else if (position <= 1) {//(0,1]
            float scaleFactor =  MIN_SCALE+(1-Math.abs(position))*(MAX_SCALE-MIN_SCALE);
            page.setScaleX(scaleFactor);
            page.setScaleY(scaleFactor);
        } else {//(1,Infinity)
            page.setScaleX(MIN_SCALE);
            page.setScaleY(MIN_SCALE);
        }
    }
}
3、在BannerView.java 的initAttribute()获取isScale：
  mIsScale=typedArray.getBoolean(R.styleable.BannerView_isScale, mIsScale);

在initView()中设置：
 if(mIsScale){
                mBannerViewPager.setPageTransformer(true, new BannerTransformer());
            }
